RustAudio/rust-lv2

- lv2-core/lv2-core-derive/src/lib.rs
- lv2-core/lv2-core-derive/src/lv2_descriptors.rs
- lv2-core/lv2-core-derive/src/lv2_ports_derive.rs
- lv2-core/src/feature/descriptor.rs
- lv2-core/src/feature/feature.rs
- lv2-core/src/feature/list.rs
- lv2-core/src/lib.rs
- lv2-core/src/plugin.rs
- lv2-core/src/plugin/features.rs
- lv2-core/src/plugin/plugin.rs
- lv2-core/src/plugin/ports.rs
- lv2-core/src/plugin_descriptor.rs
- lv2-core/src/port.rs
- lv2-core/src/ports/audio.rs
- lv2-core/src/ports/base.rs
- lv2-core/src/ports/control.rs
- lv2-core/src/ports/cv.rs
- lv2-core/src/uri.rs
- lv2/examples/amplifier/lib.rs
My main goal is to improve the `Plugin::instantiate` implementation: First, information like the frame rate, the bundle path or the URI of the plugin should be passed to the plugin. Therefore, I needed to extend the trait as well as the `Plugin::instantiate` implementation; Both reside in lv2-core/src/plugin/plugin.rs. While I was at it, I also updated the error management: In short, you already did the right thing: If the plugin can't be instantiated, the instantiate method should simply return a null pointer, that's expected behavior (as noted in the [spec](http://lv2plug.in/doc/html/group__lv2core.html#a8dbb1fd9ebae0477a11dfc4f0a685d72)).
Lastly, I accidentally ran `cargo fmt`. It did a lot of things, but I don't think that having consistent code formatting is a bad thing, isn't it?
> Running "cargo fmt" and improving Plugin::instantiate

- core/src/plugin/info.rs
- core/src/plugin/mod.rs
- tests/amp.rs
The plugin's `new` function now takes three extra parameters that are data given from the host, which may or may not be used.
I put all of these in a single struct, for the following reasons:
- It makes it so you don't have to list and import all of the arguments if you don't use them (`Uri`, `CStr`, `Path`)
- It avoids leaking implementation details in the signature of this method of the trait (I also changed `bundle_path` to a `&Path` instead of a `&CStr`, so it can be used directly from Rust code to access the bundle without converting it first).
- It allows to add more data, fields or helpers to the instantiation function without it being a breaking change.
However I am aware that `PluginInfo` is not a good name for this struct, it is definitely up for bikeshedding. …
> Use a single struct to hold all plugin instanciation information

- core/src/extension_data.rs
- core/src/feature/mod.rs
- core/src/port/audio.rs
- core/src/port/control.rs
- core/src/port/cv.rs
- core/src/port/mod.rs
I've noticed that there are many (three) traits that also include a URI constant. In one case, `UriBound` is implemented for all implementors of that trait, but in all of the other cases, not. I therefore remove the `URI` constants from these traits and added `UriBound` as a super-trait. This should be a bit cleaner and easier to detect by RLS.
> Removing hand-written URI constants with `UriBounds`

- core/derive/Cargo.toml
- core/derive/src/lib.rs
- core/derive/src/lv2_descriptors.rs
- core/derive/src/lv2_ports_derive.rs
- core/derive/src/port_container_derive.rs
- core/src/plugin/mod.rs
- tests/amp.rs
We should start to test and document your code now. First, I picked up the macro code, because this is the part I'm least familiar with. I've learned quite a bit from it and I hope that the descriptions are correct and without typos!
I also thought about the names for related things and renamed some internal stuff for the macros. However, I did not like the name `Lv2Ports`, especially because it contains a mention of LV2. Therefore, I renamed it into `PortContainer`, which I find more descriptive and style-fitting.
> Documenting the macros and renaming several things

- core/src/extension.rs
- core/src/extension_data.rs
- core/src/lib.rs
- core/src/plugin/mod.rs
- core/tests/extension.rs
Implementation is functional, but can maybe be cleaned up a bit, and still needs documentation!
> WIP: First implementation for LV2 Extensions system

- core/src/extension.rs
- core/src/feature.rs
- core/src/lib.rs
- core/src/plugin/info.rs
- core/src/plugin/mod.rs
- core/src/prelude.rs
- core/tests/amp.rs
- urid/src/feature.rs
- urid/src/mapper.rs
This PR brings back the `Uri` (and `UriBuf`) types, but as simple type aliases instead of newtype wrappers.
This does not add any boilerplate (in both the implementing and user side of things), and allows e.g. this:
```rust
fn unmap(&self, urid: URID) -> &CStr { /* ... */ }
```
to become this:
```rust
fn unmap(&self, urid: URID) -> &Uri { /* ... */ }
```
This has the advantage to make all APIs much clearer just by looking at the function signatures, as it is quite odd to be handling FFI types in normal (high-level, safe) APIs, especially for newer users.
> Add an Uri type alias.

- core/sys/Cargo.toml
- units/sys/Cargo.toml
- urid/sys/Cargo.toml
This is a simple change that makes `-sys` crates use `bindgen` without its default features (mainly `clap`), which are useless to us since we only use it as a library. :slightly_smiling_face: 
It is a small change, but on my system this makes the release build time go from `2m5s` to `1m31s`, without losing any feature we actually need, which is quite nice!
> Use bindgen without its default features to make builds lighter

- units/src/lib.rs
- urid/derive/src/urid_cache_derive.rs
- urid/src/feature.rs
- urid/src/lib.rs
- urid/src/urid.rs
- urid/tests/urid.rs
While I was creating an integration test for atom, I saw potential to make `use` clauses simpler: You often have to `use` every single type you need on your own, which may be a bit frustrating when you've just started to work with rust-lv2. Therefore, I put all of the things you need to to `use` in preludes. I hope you're okay with that change!
> Improving the preludes

- core/derive/Cargo.toml
- core/sys/Cargo.toml
- units/sys/Cargo.toml
- urid/derive/Cargo.toml
- urid/sys/Cargo.toml
This pulls in the latest update of bindgen, which contains some work I did in harryfei/which-rs#14 and rust-lang/rust-bindgen#1625 to further reduce the amount of indirect dependencies we have, and thus build times as well. :slightly_smiling_face: 
Basically, `bindgen` depends on the `which` crate, which had a mandatory dependency on `failure` which `bindgen` did not use at all. I removed the dependency in those two PRs, making all `bindgen` users free of having to pull `failure` as well as its own dependencies (most problematic being `backtrace`).
For us, this removes another 10 seconds of build times on my machine (from `1m28s` to `1m18s`). :slightly_smiling_face: 
This PR also updates the `syn` and `quote` crates to their `1.0` version, as I noticed `bindgen` depended on them as well, …
> Update bindgen to make builds (even!) lighter

- .travis.yml
- core/derive/src/feature_collection_derive.rs
- core/src/feature/container.rs
- core/src/feature/core_features.rs
- core/src/feature/descriptor.rs
- core/src/feature/mod.rs
- core/tests/amp.rs
- urid/src/feature.rs
- urid/src/mapper.rs
- urid/src/urid.rs
- urid/tests/urid.rs
Okay, this is a bit weird because I'm reverting some of your changes, but I have good reasons to do so:
At first, I didn't like the `cast_feature_ref` function because it is written without a context, like a type or trait. But secondly and more importantly, it creates a dummy reference to a generally unknown but zero-sized type if the provided pointer points to null. This is very wrong since the reference isn't actually of the given type and therefore, it technically isn't valid.
The first thing could easily be fixed: Move that function inside the `Feature` trait and you're done. The second thing didn't went so easy, because it's roots lie in a design decision: The feature container always has to contain references to the features and this simply doesn't work: Some feature's data pointer …
> Refactoring the feature system to remove the `cast_feature_ref` function

- core/src/plugin/mod.rs
This change fixes an unsoundness issue discovered by [YruamaLairba](https://github.com/YruamaLairba).
The problem is that the external methods of an extension need to cast the `LV2_Handle` they receive from the host to a Rust type in order to use them. Currently, the plugin instance the host deals with has the type `PluginInstance<P>`, where `P` is the type of the plugin. Therefore, an external extension method would need to cast the `LV2_Handle` to `*mut PluginInstance<P>`.
However, I didn't think about that when I wrote the `State` extension and casted the `LV2_Handle` to `*mut P`, which may be unsound since `PluginInstance` is `repr(Rust)` and therefore a pointer to an instance of this struct may or may not be a pointer to `P` too.
I could fix that in this instance, but others might …
> Assuring that a LV2_Handle is a valid plugin pointer

- atom/tests/atom_integration.rs
- core/derive/src/feature_collection_derive.rs
- core/src/extension.rs
- core/src/feature/cache.rs
- core/src/feature/core_features.rs
- core/src/feature/descriptor.rs
- core/src/feature/mod.rs
- core/src/plugin/mod.rs
- core/src/prelude.rs
- core/tests/amp.rs
- state/src/interface.rs
- state/src/lib.rs
- state/tests/integration.rs
- urid/src/feature.rs
These changes allow plugin methods to access host features and also allows features to limit themselves to specific threading classes.
According to the [core LV2 specifications](https://lv2plug.in/ns/lv2core/lv2core.html), there are three threading classes: "Discovery", "Instantiation", and "Audio". Features are discovered in the "Instantiation" class and therefore, only "Instantiation" and "Audio" methods are able to access host features.
Since we also want to limit certain features to certain threading classes, or disallow them in others, I've split the `Features` type definition in the `Plugin` trait to `InitFeatures` and `AudioFeatures`. During instantiation, these feature collections are created and stored in the `PluginInstance`. Then, all methods get access to their respective …
> Making features available for all methods

- README.md
- atom/src/object.rs
- atom/tests/atom_integration.rs
- core/README.md
- core/src/extension.rs
- core/tests/amp.rs
- state/src/interface.rs
- urid/derive/Cargo.toml
- urid/derive/src/lib.rs
- urid/derive/src/uri_bound.rs
- urid/derive/src/urid_collection_derive.rs
- urid/derive/tests/uri_bound.rs
- urid/lv2-urid/tests/urid.rs
- urid/src/lib.rs
- urid/tests/urid.rs
This pull request closes #46 by adding a procedural macro that implements `UriBound` for a type.
The syntax looks like that:
```Rust
#[uri("https://google.com")]
struct Google;
```
This macro parses the argument, assures that it is a ASCII string literal, adds a null terminator and uses this URI to implement `UriBound`. It is only useful for non-generic types where the URI is given as a literal. Most of the `UriBound` implementation in the project use URIs from the `lv2-sys` crate and therefore don't need such a macro, and supporting generics would require a lot of detailed token tree manipulations that aren't needed for the general case.
I really struggled with this goal the last time I tried it, but now, it was rather easy.
> Adding a `uri` attribute

- Cargo.toml
- src/lib.rs
This pull request boosts the usability of the root re-export crate. Instead of simply depending on all sub-crates and re-exporting them via `pub extern crate`, it now optionally depends on all crates and `pub use`s them. This leads to multiple quality-of-life enhancements:
* Plugin creators only need to depend on one crate, but still
* have the choice which crates to use,
* see a clear module <-> specification relationship.
* Plugin creators don't need to investigate which sub-crates received updates and change their `Cargo.toml` accordingly. They only need to update the dependency to `lv2`.
* Feature sets can be created for common scenarios. I've already included a minimal plugin set and a standard plugin set, but in the future, there could also be a host set.
* The internal structures …
> Improving the re-export crate

- atom/src/lib.rs
- core/derive/src/lv2_descriptors.rs
- core/derive/src/port_collection_derive.rs
- core/src/extension.rs
- core/src/prelude.rs
- urid/derive/src/uri_bound.rs
- urid/derive/src/urid_collection_derive.rs
This pull requests makes all macros unhygenic. To be more precise: With this pull request, all macros depend that the surrounding scope is `use`ing the right prelude module.
This fixes the problem that the macros don't work anymore when used through the re-export crate. Updated documentation is about to follow.
> Making all macros unhygenic

- atom/Cargo.toml
- atom/src/lib.rs
- atom/src/object.rs
These are some small enhancement for `lv2-atom` I introduced for the metronome example:
* The `UnidentifiedAtom` has a method to retrieve the type URID of the atom. That might be useful for debugging or to identify an atom without actually reading it.
* `Blank` isn't deprecated anymore since it conveyed the wrong meaning: Some "older" hosts (e.g. Carla) send `Blank` objects instead of regular objects and a plugin has to retrieve both. They are deprecated in a way that a new plugin shouldn't send them, but plugins should also accept them and `Blank`s won't be removed anytime soon.
> Atom tweaks

- core/src/feature/cache.rs
- core/src/plugin/mod.rs
- worker/src/lib.rs
This PR is a reply to #62 and solves the bug that a feature can not be used both in the `InitFeatures` collection and the `AudioFeatures` collection. My solution is to clone the feature cache before the `InitFeatures` are retrieved and then to retrieve the `AudioFeatures` from the clone.
This is sound since there may never be two mutable references to the same feature outside of `PluginInstance`: The core plugin methods only receive a mutable reference to the feature collections and therefore can not keep a reference to a feature outside of these methods. Extensions can only retrieve the plugin either with the `InitFeatures` or the `AudioFeatures`, but not both at the same time.
> Cloning the features cache to allow features to be used in both feature collections

- docs/amp/Cargo.toml
- docs/fifths/Cargo.toml
- docs/metro/Cargo.toml
- docs/metro/src/pipes.rs
- docs/midigate/Cargo.toml
- install_examples.sh
I've discovered and fixed a) why all example plugins haven't been working lately and b) why @YruamaLairba and I reported different library sizes for the plugins: The `dylib` crate type now creates a dynamic library which supposed to be loaded by a Rust program and therefore dynamically links to the current `std` library. Libraries that are supposed be loaded by non-Rust programs should use the `cdylib` crate type now, which creates distributable shared libraries. They are about 0.9 MB in size, which is okay from my point of view.
I've also fixed a bug in the metro plugin that ignored all events with an index of 0.
> Fixing the examples

- urid/derive/Cargo.toml
- urid/derive/src/uri_bound.rs
I tried to remove regex from dependency graph to reduce compilation time. On my computer, It take 26s instead 38 in debug and 1min14 instead 1min54. More than 30% of time-saving.
> Replace regex usage by function from std

- docs/README.md
- install_examples.sh
The way the installation script handles targets is faulty.
Now, the first argument of the script is interpreted as the target to build and if it's left out, no target flag is used at all.
> Fixing the installation script

- Cargo.toml
- README.md
- sys/Cargo.toml
- sys/src/lib.rs
This basically mimics the [platform support scheme of rustc](https://doc.rust-lang.org/nightly/rustc/platform-support.html) and hopefully makes clear what to expect on which targets. I've also removed the experimental targets feature since rustc doesn't have such a guard too, which would break the parallelism in the scheme.
> Rewording the target suport into tiers

- atom/tests/atom_integration.rs
- core/src/extension.rs
- core/src/lib.rs
- core/src/plugin/mod.rs
- core/tests/amp.rs
- docs/amp/src/lib.rs
- docs/fifths/src/lib.rs
- docs/metro/src/lib.rs
- docs/midigate/src/lib.rs
- src/lib.rs
- state/src/interface.rs
- state/src/lib.rs
- state/src/path.rs
- state/tests/integration.rs
- worker/src/lib.rs
This adds `sample_count` to the Plugin trait. This is necessary if the plugin needs to be correct regarding samples/frames, but has no audio port and no direct access to the number of frames (e.g. a sequencing plugin which has just midi ports, but needs to emit events at exact frames).
See also #87 for discussion.
> Add sample_count to Plugin run method

- core/derive/src/port_collection_derive.rs
Currently, rust-analyzer complains:
```
Structure `__lv2_plugin_ports_derive_Ports_PortPointerCache` should have CamelCase name, e.g. `Lv2PluginPortsDerivePortsPortPointerCache`
```
As of [this commit](https://github.com/rust-analyzer/rust-analyzer/pull/6421/files), rust-analyzer will honor `allow(non_camel_case_types)`, so I'm trying to add it here. I have no idea if this actually works though.
> Add allow(non_camel_case_types) to generated type

- docs/midigate/src/lib.rs
Hi, found and fixed an error in midigate example. This error result in crash with the following conditions:
host : jalv or ardour, with inPlaceBroken removed from the midigate.ttl for the test.
sending many notes to the plugin. Making a "glissando" with Jack keyboard is generally enough
> fix offset calculation in midigate
